name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: individual-assignment
  AZURE_WEBAPP_RG: centcol

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
